# Configuration Certstream
certstream:
  url: "ws://certstream-server:8080/domains-only"
  exclusions:
    - .ui.com
    - .imperva.com
    - .nflxvideo.net

# Configuration des APIs pour les wildcards
apis:
  - name: "primary-scopes"
    url: "https://scopes.jomar.ovh"
    headers:
      X-API-Key: "<value>"
      Content-Type: "application/json"
    enabled: true

wildcards_update_interval: 86400

# Configuration du sondage HTTP
http:
  ports:
    - protocol: "http"
      port: 80
    - protocol: "https"
      port: 443
    - protocol: "http"
      port: 8080
    - protocol: "https"
      port: 8443
  timeout: 5

# Configuration Fingerprinter
fingerprinter:
  url: "https://fingerprinter.jomar.ovh/fingerprint"
  api_key: "<value>"
  callback_urls:
    - "https://recon.jomar.ovh/api/fingerprinter?token=<value>"

# Notifications Discord
discord:
  messages_webhook: "https://discord.com/api/webhooks/<value>/<value>"
  logs_webhook: "https://discord.com/api/webhooks/<value>/<value>"
  stats_interval: 10800

# Configuration des logs
logging:
  level: "INFO"
  console_colors: true

# Configuration du shutdown
shutdown:
  timeout: 30
