# Configuration file for Certstream monitor

# API Configuration
api:
  url: http://scopes.jomar.ovh
  headers:
    X-API-Key: "your-api-key-here"
  update_interval: 86400 # 24 hours in seconds

# Certstream Configuration
certstream:
  url: "ws://certstream-server:8080/domains-only"
  exclusions:
    - ui.com
    - imperva.com
    - nflxvideo.net

# Fingerprinter Configuration
fingerprinter:
  url: "http://fingerprinter.tld"
  callback_url: "http://callback_url"
  api_key: ""

# Database Configuration
database:
  path: "./data/certstream.db"
  retry_interval: 10800 # 3 hours in seconds
  max_retries: 336 # 14 days worth of retries (112 * 3 hours)

# Discord Configuration
discord:
  messages_webhook: "your-webhook-url-here"
  logs_webhook: "your-webhook-url-here"
  username: "Certstream Monitor"

# Logging Configuration
logging:
  level: "info" # debug, info, warn, error, fatal
  file: "./logs/certstream.log"

# Concurrency Configuration
concurrency:
  min: 20
  max: 40
